# -*- coding: utf-8 -*-
"""Projeto de BigData Analise clima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBcnsEhsFtoec4ceJl0_loKsm7oucdrx
"""

import pandas as pd
import matplotlib.pyplot as plt
import glob

# 1. Listar todos os arquivos CSV no diretório atual
arquivos_csv = glob.glob("*.csv")

# 2. Armazenar os resultados em uma lista
medias = []

# 3. Iterar sobre cada arquivo para calcular a média de poluentes
for arquivo in arquivos_csv:
    try:
        df = pd.read_csv(arquivo, encoding='latin1')
        df['valor'] = pd.to_numeric(df['valor'], errors='coerce')  # força conversão numérica
        df = df.dropna(subset=['valor'])  # remove valores não numéricos

        media = df['valor'].mean()
        medias.append((arquivo, media))

    except Exception as e:
        print(f"Erro ao ler {arquivo}: {e}")

# 4. Criar DataFrame com as médias
df_medias = pd.DataFrame(medias, columns=['arquivo', 'media_valor'])

# 5. Identificar o arquivo com maior média
arquivo_top = df_medias.loc[df_medias['media_valor'].idxmax()]

# 6. Exibir resultados no terminal
print("\nArquivo com maior média de poluentes:")
print(f"{arquivo_top['arquivo']} - Média: {arquivo_top['media_valor']:.2f}")

print("\nTodas as médias por arquivo:")
print(df_medias)

# 7. Gerar gráfico de barras
plt.figure(figsize=(10, 6))
bars = plt.bar(df_medias['arquivo'], df_medias['media_valor'], color='steelblue')

# Destacar o maior com outra cor
for bar, nome in zip(bars, df_medias['arquivo']):
    if nome == arquivo_top['arquivo']:
        bar.set_color('crimson')
        bar.set_label(f"Maior média: {nome}")

# 8. Configurações do gráfico
plt.title('Média de Poluentes por Arquivo CSV')
plt.xlabel('Arquivo')
plt.ylabel('Média dos Valores dos Poluentes')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import glob

# 1. Lista de arquivos CSV no diretório atual (ajuste o caminho conforme necessário)
arquivos_csv = glob.glob("*.csv")  # ou ex: glob.glob("dados/*.csv")

# 2. Lê e combina todos os arquivos
dataframes = []
for arquivo in arquivos_csv:
    try:
        df = pd.read_csv(arquivo, encoding='latin1')
        dataframes.append(df)
    except Exception as e:
        print(f"Erro ao ler {arquivo}: {e}")

# 3. Concatena todos os DataFrames em um único
df_total = pd.concat(dataframes, ignore_index=True)

# 4. Agrupar por poluente e calcular a média
df_poluentes = df_total.groupby('poluente')['valor'].mean().reset_index()

# 5. Ordenar do mais para o menos poluente
df_poluentes_sorted = df_poluentes.sort_values(by='valor', ascending=False)

# 6. Exibir os resultados
print(df_poluentes_sorted)

# 7. (Opcional) Gráfico
plt.figure(figsize=(10, 6))
plt.bar(df_poluentes_sorted['poluente'], df_poluentes_sorted['valor'], color='darkgreen')
plt.title('Média dos Valores por Poluente (Arquivos combinados)')
plt.xlabel('Poluente')
plt.ylabel('Valor Médio')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# 1. Leitura do dataset
arquivo_csv = 'RJ202201.csv'  # Altere conforme necessário
df = pd.read_csv(arquivo_csv, encoding='latin1')

# 2. Agrupar por estação e calcular média dos valores
df_grouped = df.groupby('estacao')['valor'].mean().reset_index()

# 3. Plotar gráfico
plt.figure(figsize=(14, 6)) # Altere o tamanho de acordo com seu dado
plt.bar(df_grouped['estacao'], df_grouped['valor'], color='blue')
plt.title('Média dos Valores por Estação')
plt.xlabel('Estação')
plt.ylabel('Valor Médio')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# 1. Leitura do dataset
arquivo_csv = 'PE2022.csv'  # Altere se necessário
df = pd.read_csv(arquivo_csv, encoding='latin1')

# 2. Agrupar por poluente e calcular a média dos valores
df_grouped = df.groupby('poluente')['valor'].mean().reset_index()

# 3. Plotar gráfico de barras
plt.figure(figsize=(10, 6))
plt.bar(df_grouped['poluente'], df_grouped['valor'], color='skyblue')
plt.title('Média dos Valores por Tipo de Poluente')
plt.xlabel('Poluente')
plt.ylabel('Valor Médio')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# 1. Leitura do dataset
arquivo_csv = 'SP202202.csv'  # Substitua pelo nome/caminho do seu arquivo
df = pd.read_csv(arquivo_csv, encoding='latin1')

# 2. Agrupar por data e calcular a média dos valores
df['data'] = pd.to_datetime(df['data'], format='%Y-%m-%d')
df_grouped = df.groupby('data')['valor'].mean().reset_index()

# 3. Plotar gráfico da evolução dos valores
plt.figure(figsize=(14, 6))
plt.plot(df_grouped['data'], df_grouped['valor'], marker='o', linestyle='-')
plt.title('Evolução dos Valores Médios de Poluentes por Data')
plt.xlabel('Data')
plt.ylabel('Valor Médio')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""pip install pyspark pandas matplotlib"""